### ISSUE TITLE
Notification Services don't send Mails because Strategies are not saved

### ISSUE THREAD

**Issue by vertexvaar** [TYPO3-Caretaker/caretaker#93] opened 2018-01-02 12:33 UTC
The caretaker server does not send notification mails anymore. After hours of debugging i found that it is not possible to select notification strategies in the backend. The TCA responsible for the field looks very weird to me, especially for a type `inline` so that might be the cause of this broken behaviour.
(There is not a single entry in the table configured in the TCA)

Versions:
* TYPO3: 7.6
* caretaker: dev-master
* PHP: 5.5

**Comment by TehTux** [comment] 2019-08-22 10:21
Duplicate of #75 

You can create a second "dummy" strategy. Than you can select one.

**Closed** 2019-08-22 10:22 UTC
